filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true

filebeat.config.inputs:
  enabled: true
  # path: /usr/share/filebeat/inputs/*.yml
  path: /var/lib/graylog-sidecar/generated/*/*.conf
  reload.enabled: true

filebeat.autodiscover:
  providers:
  - type: docker
    hints.enabled: true
    host: "unix:///var/run/docker.sock"
    hints.default_config:
      type: filestream
      id: container-${data.container.id}
      prospector.scanner.symlinks: true
      parsers:
        - container: ~
      paths:
        - /var/lib/docker/containers/${data.container.id}/*.log

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

output.logstash:
  hosts: ["graylog:5044"]
  
logging.level: error
logging.to_stderr: true