services:
  ghost:
    restart: unless-stopped
    image: ghost:5-alpine
    ports:
      - 127.0.0.1:8080:2368 # Listen on Real "localhost" interface
      - 172.17.0.1:8080:2368 # Listen on Docker "localhost" interface
    environment:
      - database__client=${GHOST_DB_CLIENT}
      - database__connection__host=${GHOST_DB_HOSTNAME}
      - database__connection__user=${GHOST_DB_USER}
      - database__connection__password=${MYSQL_ROOT_PASSWORD}
      - database__connection__database==${GHOST_DB_NAME}
    volumes:
      - ghost:/var/lib/ghost/content
    depends_on: 
      mysql:
        condition: service_healthy

  mysql:
    restart: unless-stopped
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

volumes:
  ghost: {}
  mysql: {}

networks:
  default:
    external: true
    name: observability