services:
  victoriametrics:
    restart: unless-stopped
    image: victoriametrics/victoria-metrics:v1.121.0
    ports:
      - 127.0.0.1:8428:8428
    volumes:
      - vmdata:/storage
    command:
      - "--storageDataPath=/storage"
      - "--httpListenAddr=:8428"
      - "--retentionPeriod=7d"
    labels:
       vm-job: victoriametrics

  vmagent:
    restart: unless-stopped
    image: victoriametrics/vmagent:v1.121.0
    depends_on:
      - "victoriametrics"
    ports:
      - 127.0.0.1:8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./configs/vmagent.yaml:/etc/vmagent/vmagent.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - "--promscrape.config=/etc/vmagent/vmagent.yaml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
    labels:
      vm-job: vmagent
    env_file: ../.env

  grafana:
    restart: unless-stopped
    image: grafana/grafana:12.0.2
    depends_on:
      - "victoriametrics"
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/datasource.yaml:/etc/grafana/provisioning/datasources/single.yml
      - ./provisioning/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/var/lib/grafana/dashboards
    env_file: ../.env

volumes:
  vmagentdata: {}
  vmdata: {}
  grafanadata: {}

networks:
  shared:
    name: shared