metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

metricbeat.modules:
- module: elasticsearch
  period: 10s
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: false

- module: kibana
  metricsets:
    - stats
  period: 10s
  hosts: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  enabled: true


metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - uptime
    - core
    - diskio
    - filesystem
    - fsstat
  enabled: true
  period: 10s
  processes: ['.*']
  cpu.metrics:  ["percentages","normalized_percentages"]
  core.metrics: ["percentages"]

- module: mysql
  metricsets:
   - status
  period: 10s
  hosts: ["tcp(mysql:3306)/"]
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
  enabled: true

- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
    #- "network_summary"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
 - add_host_metadata: ~ 
 - add_docker_metadata: ~

output.elasticsearch:
 hosts: ${ELASTIC_HOSTS}
 username: ${ELASTIC_USER}
 password: ${ELASTIC_PASSWORD}
#  index: "metrics"

# output.elasticsearch.index: "metrics"
# setup.template.name: "metrics"
# setup.template.pattern: "metrics"

logging.level: warning
logging.to_stderr: true