target: all,alertmanager
multitenancy_enabled: true

compactor:
  data_dir: /tmp/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist
    replication_factor: 1

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /data/blocks-storage
  bucket_store:
    sync_dir: /data/bucket-store-sync
  tsdb:
    dir: /data/tsdb

server:
  http_listen_port: 9009
  log_level: warn

limits:
  compactor_blocks_retention_period: 7d
  ruler_max_rules_per_rule_group: 100


ruler:
  rule_path: /data/ruler # Temporary storage for Ruler
  alertmanager_url: http://localhost:9009/alertmanager
  ring:
    heartbeat_period: 2s
    heartbeat_timeout: 10s

ruler_storage:
  backend: filesystem
  filesystem:
    dir: /data/rules

alertmanager:
  fallback_config_file: /etc/alertmanager.yaml
  data_dir: /tmp/alertmanager # Temporary storage for Alertmanager
  external_url: http://localhost:9009/alertmanager

alertmanager_storage:
  backend: filesystem
  filesystem:
    dir: /data/alertmanager