global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "docker-containers"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_docker_container_label_vm_job]
        regex: .+
        action: keep
      - regex: __meta_docker_container_label_vm_(.+)
        action: labelmap
        replacement: $1
      - source_labels: [__address__, __meta_docker_container_label_vm_scrape_port]
        target_label: __address__
        regex: (.+):\d+;(.+)
        replacement: $1:$2
      - source_labels: [__meta_docker_container_name]
        regex: '/(.+)'
        target_label: instance
        replacement: $1
      - target_label: site
        replacement: prod

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://host.docker.internal:8080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
      - target_label: site
        replacement: prod